// Dados centrais da Nuxem — tudo que as páginas usam vem daqui.
// Fatos vindos do site antigo e do fundador; nada inventado.

export const EMPRESA = {
  nome: 'Nuxem',
  dominio: 'https://nuxemoil.com.br',
  whatsappPrincipal: '5511915011527',
  whatsappSecundario: '5511945868799',
  telefone: '(11) 97462-0945',
  email: 'contato@nuxemoil.com',
  endereco: 'Av Brasília, 2242 - Vila Norma, Salto/SP, CEP 13327-896',
  cnpj: '47.626.641/0001-10',
  regiao: 'todo o estado de São Paulo',
  cidades: 'Grande São Paulo, Campinas, Sorocaba, Jundiaí, Piracicaba e Ribeirão Preto',
  diferenciais: [
    { titulo: 'Atendimento 24h', texto: 'Suporte e atendimento a qualquer hora, todos os dias. Operação térmica não espera horário comercial.' },
    { titulo: 'Frota própria', texto: 'Entrega rápida com caminhões próprios, sem depender de terceiros para cumprir prazo.' },
    { titulo: 'Produção sob demanda', texto: 'Combustível produzido conforme a necessidade da sua operação, com padrão constante de qualidade.' },
    { titulo: 'Preço competitivo', texto: 'Alta qualidade com custo justo, para reduzir o custo térmico da sua planta.' },
  ],
};

export const PRODUTOS = [
  {
    slug: 'oleo-bpf',
    nome: 'Óleo BPF',
    imagem: 'produto-oleo-bpf.jpg',
    imagemAlt: 'Óleo BPF sendo despejado em béquer de laboratório, mostrando sua alta viscosidade',
    resumo: 'Combustível industrial pesado, de alto poder calorífico, para operações de alta demanda energética.',
    title: 'Óleo BPF em São Paulo | Fornecedor com Entrega Rápida | Nuxem',
    description: 'Compre óleo BPF com qualidade, entrega rápida e atendimento 24h em todo o estado de São Paulo. Frota própria e produção sob demanda. Solicite cotação.',
    specs: [
      ['Viscosidade', 'Alta'],
      ['Poder calorífico', 'Acima de 10.400 kcal'],
      ['Ponto de fluidez', '18 ºC a 27 ºC'],
      ['Ponto de fulgor', 'Acima de 66 ºC'],
      ['Aspecto', 'Líquido escuro e viscoso'],
    ],
    aplicacoes: 'Caldeiras, fornos industriais, usinas de asfalto e fundições.',
    corpo: [
      'O óleo BPF (Baixo Ponto de Fluidez) é um combustível industrial derivado de petróleo, amplamente utilizado como fonte de energia térmica em caldeiras, fornos, secadores e usinas de asfalto. Seu alto poder calorífico o torna a escolha padrão para operações que exigem queima contínua e alta carga energética.',
      'A Nuxem fornece óleo BPF com padrão constante de qualidade e produção sob demanda: o combustível é preparado conforme a necessidade da sua operação, com rastreabilidade e suporte técnico para especificação correta de viscosidade, aquecimento de linha e atomização.',
      'Atendemos todo o estado de São Paulo com frota própria e atendimento 24 horas — porque uma planta térmica parada por falta de combustível custa muito mais do que o próprio combustível.',
    ],
  },
  {
    slug: 'oleo-apf',
    nome: 'Óleo APF',
    imagem: 'produto-oleo-apf.jpg',
    imagemAlt: 'Óleo APF fluido sendo despejado em béquer, mostrando sua baixa viscosidade',
    resumo: 'Combustível industrial leve, de baixa viscosidade, que dispensa aquecimento prévio.',
    title: 'Óleo APF – Combustível Industrial Leve | Nuxem São Paulo',
    description: 'Óleo APF de baixa viscosidade, sem necessidade de aquecimento, para caldeiras, fornos e usinas de asfalto. Entrega rápida em SP. Solicite cotação.',
    specs: [
      ['Viscosidade', 'Baixa'],
      ['Poder calorífico', 'Acima de 10.400 kcal'],
      ['Ponto de fulgor', 'Acima de 60 ºC'],
      ['Aspecto', 'Líquido escuro fino'],
    ],
    aplicacoes: 'Caldeiras, fornos industriais, usinas de asfalto e fundições.',
    corpo: [
      'O óleo APF (Alto Ponto de Fluidez) é um combustível industrial leve, de baixa viscosidade, que dispensa sistemas de aquecimento para bombeamento e queima. Isso simplifica a operação e reduz custo em plantas que não possuem linha aquecida.',
      'Com poder calorífico equivalente ao do BPF, o APF é indicado para equipamentos que exigem atomização eficiente e partidas rápidas, mantendo estabilidade de chama e queima limpa.',
      'A Nuxem entrega óleo APF em todo o estado de São Paulo com frota própria, produção sob demanda e suporte técnico para avaliar a compatibilidade com seu equipamento.',
    ],
  },
  {
    slug: 'oleo-b1',
    nome: 'Óleo B1 (OC-B1)',
    imagem: 'produto-oleo-bpf.jpg',
    imagemAlt: 'Óleo B1 OC-B1 sendo despejado em béquer de laboratório',
    resumo: 'Óleo combustível de baixo teor de enxofre, ideal para indústrias com exigência ambiental.',
    title: 'Óleo B1 (OC-B1) em São Paulo | Fornecedor Industrial | Nuxem',
    description: 'Fornecemos óleo combustível B1 OC-B1 para caldeiras e fornos industriais em SP. Baixo teor de enxofre, alta eficiência térmica. Solicite cotação.',
    specs: [
      ['Viscosidade cinemática a 60°C', 'Máx. 620 cSt'],
      ['Teor de Enxofre', 'Máx. 1% em massa'],
      ['Poder Calorífico Superior', '> 10.000 kcal/kg'],
      ['Ponto de Fulgor', '> 66°C'],
      ['Classificação ANP', 'Tipo B (OC-B1)'],
    ],
    aplicacoes: 'Caldeiras a vapor, fornos industriais, geração de energia térmica, aquecimento de processos, queimadores industriais, usinas de asfalto.',
    corpo: [
      'O Óleo B1 (OC-B1) é um óleo combustível de baixo teor de enxofre (máximo 1% em massa), classificado pela ANP como tipo B, ideal para indústrias que buscam redução de emissões sem abrir mão do alto desempenho energético.',
      'Com viscosidade máxima de 620 cSt a 60°C e poder calorífico superior a 10.000 kcal/kg, atende os limites da Resolução CONAMA 491/2018, sendo a escolha certa para operações que precisam de conformidade ambiental.',
      'A Nuxem fornece óleo B1 com padrão constante de qualidade e produção sob demanda, garantindo rastreabilidade total e suporte técnico para especificação correta.',
    ],
  },
  {
    slug: 'oleo-a1',
    nome: 'Óleo A1 (OC-A1)',
    imagem: 'produto-oleo-bpf.jpg',
    imagemAlt: 'Óleo A1 OC-A1 combustível industrial pesado',
    resumo: 'Óleo combustível pesado tipo A1, alto poder calorífico, para caldeiras, fornos e usinas de asfalto.',
    title: 'Óleo A1 (OC-A1) em São Paulo | Fornecedor de Óleo BPF A1 | Nuxem',
    description: 'Óleo combustível A1 OC-A1 para queima industrial em caldeiras, fornos e usinas de asfalto. Alto poder calorífico, viscosidade controlada. Entrega rápida em SP.',
    specs: [
      ['Viscosidade cinemática a 60°C', 'Máx. 620 cSt'],
      ['Teor de Enxofre', 'Máx. 2,5% em massa'],
      ['Poder Calorífico Superior', '> 10.000 kcal/kg'],
      ['Ponto de Fulgor', '> 66°C'],
      ['Classificação ANP', 'Tipo A (OC-A1)'],
    ],
    aplicacoes: 'Caldeiras industriais, fornos, usinas de asfalto, fundições, geração de energia térmica.',
    corpo: [
      'O Óleo A1 (OC-A1) é um óleo combustível pesado de alto poder calorífico, classificado pela ANP como tipo A (maior teor de enxofre, menor limite de viscosidade). É a escolha padrão para operações que exigem alta carga energética contínua.',
      'Sua viscosidade controlada permite atomização eficiente em queimadores industriais, com queima estável e alto rendimento térmico, sendo amplamente utilizado em caldeiras, fornos e usinas de asfalto.',
      'A Nuxem fornece óleo A1 com produção sob demanda e qualidade constante, com entrega em todo o estado de São Paulo.',
    ],
  },
  {
    slug: 'oleo-de-xisto',
    nome: 'Óleo de Xisto (OTE)',
    imagem: 'produto-oleo-bpf.jpg',
    imagemAlt: 'Óleo de Xisto OTE de alta fluidez',
    resumo: 'Alta fluidez, baixo teor de enxofre, dispensa pré-aquecimento. Alternativa ao petróleo.',
    title: 'Óleo de Xisto OTE em São Paulo | Fornecedor | Nuxem',
    description: 'Óleo de xisto OTE de alta fluidez, baixo teor de enxofre, dispensa pré-aquecimento. Fornecemos para caldeiras e fornos em todo estado de SP. Cotação rápida.',
    specs: [
      ['Viscosidade', 'Baixa — dispensa pré-aquecimento'],
      ['Teor de Enxofre', 'Baixo'],
      ['Poder Calorífico', 'Superior'],
      ['Fluidez em baixas temperaturas', 'Alta'],
      ['Emissão de poluentes', 'Reduzida'],
    ],
    aplicacoes: 'Caldeiras industriais, fornos, usinas de asfalto, regiões de clima frio, processos que exigem baixa emissão.',
    corpo: [
      'O Óleo de Xisto OTE é produzido a partir do xisto betuminoso, com alta fluidez mesmo em baixas temperaturas, dispensando totalmente o pré-aquecimento exigido por outros combustíveis pesados.',
      'Com baixo teor de enxofre e menor emissão de poluentes, reduz significativamente a corrosão em dutos e chaminés, prolongando a vida útil dos equipamentos.',
      'A Nuxem fornece óleo de xisto para todo o estado de São Paulo, com frota própria e atendimento 24 horas.',
    ],
  },
  {
    slug: 'oleo-bte',
    nome: 'Óleo BTE',
    imagem: 'produto-oleo-bpf.jpg',
    imagemAlt: 'Óleo BTE baixo teor de enxofre',
    resumo: 'Combustível premium baixo teor de enxofre, produzido pela Braskem. Menor emissão de fuligem.',
    title: 'Óleo BTE em São Paulo | Baixo Teor de Enxofre | Nuxem',
    description: 'Óleo BTE (Baixo Teor de Enxofre) produzido pela Braskem, combustível premium para caldeiras e fornos industriais. Menor emissão de fuligem. Entrega em SP.',
    specs: [
      ['Viscosidade a 60°C', '25 - 60 cSt'],
      ['Teor de Enxofre', 'Máx. 0,5% em massa'],
      ['Poder Calorífico Superior', '> 9.800 kcal/kg'],
      ['Ponto de Fulgor', '> 66°C'],
      ['Produção', 'Braskem'],
    ],
    aplicacoes: 'Caldeiras a vapor, fornos industriais, processos com restrição ambiental, indústrias que exigem baixa emissão de fuligem.',
    corpo: [
      'O Óleo BTE (Baixo Teor de Enxofre) é um combustível líquido premium produzido pela Braskem, com baixíssimo teor de enxofre — máximo de 0,5% em massa, sendo a opção mais limpa entre os combustíveis líquidos industriais.',
      'Com viscosidade entre 25 e 60 cSt, oferece excelente desempenho térmico aliado à menor emissão de fuligem. Ideal para processos industriais com restrições ambientais.',
      'A Nuxem fornece óleo BTE para todo o estado de São Paulo, com frota própria e atendimento 24 horas.',
    ],
  },
  {
    slug: 'oleos-alternativos',
    nome: 'Óleos alternativos',
    imagem: 'queimador-industrial.jpg',
    imagemAlt: 'Queimador industrial em operação com chama estável',
    resumo: 'Alternativas ao BPF com viscosidades diferentes e desempenho equivalente, sob medida para seu equipamento.',
    title: 'Óleos Combustíveis Alternativos ao BPF | Nuxem São Paulo',
    description: 'Óleos combustíveis alternativos ao BPF, com viscosidades variadas e desempenho equivalente. Especificação sob medida para seu equipamento. Cotação rápida.',
    specs: [
      ['Viscosidade', 'Variada, conforme a necessidade do equipamento'],
      ['Desempenho', 'Equivalente ao óleo BPF'],
      ['Produção', 'Sob demanda, com padrão de qualidade constante'],
    ],
    aplicacoes: 'Caldeiras, fornos, usinas de asfalto, fundições e demais processos térmicos industriais.',
    corpo: [
      'Nem toda operação térmica precisa — ou deve — usar o mesmo combustível. Viscosidade de trabalho, sistema de aquecimento, configuração do queimador e rotina de operação variam de planta para planta, e o combustível ideal é o que se encaixa nesse conjunto.',
      'A Nuxem fornece óleos combustíveis alternativos ao BPF, com viscosidades diferentes e qualidade equivalente. Nossa equipe avalia o seu equipamento e o seu processo para especificar o produto certo.',
      'Como a produção é sob demanda, conseguimos ajustar o fornecimento à realidade da sua operação — com entrega rápida por frota própria em todo o estado de São Paulo.',
    ],
  },
];

export const SOLUCOES = [
  {
    slug: 'usinas-de-asfalto',
    nome: 'Usinas de asfalto',
    imagem: 'hero-usina-asfalto.jpg',
    imagemAlt: 'Usina de asfalto ao entardecer com caminhão de óleo combustível',
    resumo: 'Combustível com entrega programada para a usina nunca parar por falta de abastecimento.',
    title: 'Óleo Combustível para Usina de Asfalto | Entrega em SP | Nuxem',
    description: 'Fornecimento de óleo BPF e combustíveis industriais para usinas de asfalto em São Paulo. Entrega rápida com frota própria e atendimento 24h. Solicite cotação.',
    corpo: [
      'Em uma usina de asfalto, o combustível é o coração da produção: sem calor não há secagem de agregados, não há massa asfáltica e não há obra andando. Uma falha de abastecimento para a usina, atrasa o cronograma e gera custo em cascata.',
      'Por isso a Nuxem trata o fornecimento para usinas de asfalto como operação crítica. Trabalhamos com entrega programada e frota própria, para o combustível chegar quando a produção precisa — e com atendimento 24 horas para imprevistos, porque obra não espera.',
      'Fornecemos óleo BPF e alternativas de viscosidades diferentes, com produção sob demanda e padrão constante. Nossa equipe apoia a especificação correta para o seu queimador e o seu regime de produção, em qualquer região do estado de São Paulo.',
    ],
    produtosRelacionados: ['oleo-bpf', 'oleos-alternativos', 'oleo-a1'],
    artigosRelacionados: ['oleo-combustivel-para-usina-de-asfalto', 'logistica-de-combustivel-industrial-na-pratica', 'melhores-praticas-para-abastecimento-industrial-continuo'],
  },
  {
    slug: 'caldeiras',
    nome: 'Caldeiras industriais',
    imagem: 'caldeira.jpg',
    imagemAlt: 'Caldeira industrial de geração de vapor com queimador',
    resumo: 'Queima estável e fornecimento contínuo para geração de vapor sem sustos.',
    title: 'Óleo Combustível para Caldeira Industrial | Nuxem São Paulo',
    description: 'Óleo BPF e combustíveis industriais para caldeiras com queima estável e fornecimento contínuo. Atendimento 24h em todo o estado de SP. Peça sua cotação.',
    corpo: [
      'Caldeiras industriais operam em regime contínuo, e a estabilidade da queima impacta diretamente a produção de vapor, o consumo específico e a vida útil do equipamento. Variações no combustível aparecem na chama, no rendimento e na manutenção.',
      'A Nuxem fornece óleo BPF e óleos alternativos com padrão constante de qualidade, produzidos sob demanda. Apoiamos a especificação correta para o seu sistema: viscosidade de trabalho, aquecimento de linha, temperatura de atomização e rotina de operação.',
      'Com frota própria e atendimento 24 horas, garantimos o abastecimento contínuo que uma caldeira exige — em todo o estado de São Paulo.',
    ],
    produtosRelacionados: ['oleo-bpf', 'oleo-apf', 'oleo-b1', 'oleo-bte'],
    artigosRelacionados: ['como-especificar-oleo-para-caldeira', 'melhores-combustiveis-para-caldeiras-industriais', 'principais-causas-de-instabilidade-termica'],
  },
  {
    slug: 'fundicoes',
    nome: 'Fundições',
    imagem: 'fundicao.jpg',
    imagemAlt: 'Forno de fundição vertendo metal incandescente',
    resumo: 'Alta carga térmica com consistência de processo e fornecimento confiável.',
    title: 'Óleo Combustível para Fundição | Fornecedor em SP | Nuxem',
    description: 'Combustível industrial para fundições e fornos de alta temperatura. Óleo BPF com qualidade constante, entrega rápida e suporte técnico em São Paulo.',
    corpo: [
      'Fundições trabalham com as cargas térmicas mais exigentes da indústria. A consistência do processo depende de um combustível com padrão estável: variações de qualidade aparecem em comportamento de queima, controle de temperatura e paradas não planejadas.',
      'A Nuxem fornece óleo BPF e alternativas de viscosidades diferentes para fornos de fundição, com produção sob demanda e qualidade constante entre entregas — o que protege a repetibilidade do seu processo.',
      'Nosso atendimento 24 horas e a frota própria garantem que o forno não pare por falta de combustível. Atendemos fundições em todo o estado de São Paulo, com suporte técnico na especificação.',
    ],
    produtosRelacionados: ['oleo-bpf', 'oleos-alternativos'],
    artigosRelacionados: ['oleo-pesado-para-geracao-termica-industrial', 'como-reduzir-custo-termico-industrial', 'sinais-de-combustivel-inadequado-no-processo'],
  },
];

export const HOME = {
  title: 'Nuxem | Fornecedor de Óleo BPF e Combustíveis Industriais em São Paulo',
  description: 'Fornecemos óleo BPF e combustíveis industriais para caldeiras, usinas de asfalto e fundições em todo o estado de SP. Frota própria, atendimento 24h e produção sob demanda.',
  heroTitulo: 'Óleo BPF e combustíveis industriais para sua operação não parar',
  heroTexto: 'Fornecimento para caldeiras, usinas de asfalto e fundições em todo o estado de São Paulo — com frota própria, produção sob demanda e atendimento 24 horas.',
};

export const CONTATO = {
  title: 'Contato | Solicite Cotação de Óleo Combustível | Nuxem',
  description: 'Solicite sua cotação de óleo BPF e combustíveis industriais. Atendimento 24h pelo WhatsApp, telefone ou e-mail. Entrega em todo o estado de São Paulo.',
};

export const PILAR = {
  slug: 'guia-oleo-bpf',
  title: 'Óleo BPF: Tudo que Sua Indústria Precisa Saber | Guia Completo | Nuxem',
  description: 'Guia completo sobre óleo BPF: o que é, tipos (B1, A1, BTE, Xisto), aplicações em caldeiras, usinas de asfalto e fundições, como escolher e armazenar. Tudo que sua indústria precisa saber.',
  h1: 'Óleo BPF: Tudo que Sua Indústria Precisa Saber',
  resumo: 'Guia completo sobre o principal combustível industrial do Brasil. Saiba o que é, como escolher, onde usar e como garantir o melhor fornecimento para sua operação térmica.',
  secoes: [
    {
      titulo: 'O que é Óleo BPF?',
      paragrafos: [
        'Óleo BPF significa Baixo Ponto de Fluidez. É um combustível industrial derivado de petróleo, classificado pela ANP como óleo combustível pesado, utilizado principalmente em processos de geração de energia térmica em caldeiras, fornos, usinas de asfalto e fundições.',
        'Sua principal característica é o alto poder calorífico (acima de 10.400 kcal/kg), o que o torna a escolha padrão para operações que exigem queima contínua e alta carga energética. O "baixo ponto de fluidez" significa que ele mantém fluidez em temperaturas mais baixas que outros óleos pesados, facilitando o manuseio e a queima.',
        'O óleo BPF segue a regulamentação da ANP (Resolução CNP-05) e é comercializado em diferentes classificações: tipo A (maior teor de enxofre) e tipo B (menor teor de enxofre), cada um com aplicações específicas.',
      ],
    },
    {
      titulo: 'Tipos de Óleo BPF e Combustíveis Relacionados',
      paragrafos: [
        'Existem diferentes tipos de óleo combustível industrial, cada um com características específicas de viscosidade, teor de enxofre e poder calorífico. A escolha do tipo certo depende do equipamento, da aplicação e das exigências ambientais da sua operação.',
      ],
      lista: [
        { texto: 'Óleo BPF — padrão industrial, alto poder calorífico, ideal para caldeiras e fornos', link: '/produtos/oleo-bpf/' },
        { texto: 'Óleo APF — baixa viscosidade, dispensa aquecimento prévio, fácil manuseio', link: '/produtos/oleo-apf/' },
        { texto: 'Óleo B1 (OC-B1) — baixo teor de enxofre (máx 1%), ideal para indústrias com restrição ambiental', link: '/produtos/oleo-b1/' },
        { texto: 'Óleo A1 (OC-A1) — maior teor de enxofre, alta carga energética contínua', link: '/produtos/oleo-a1/' },
        { texto: 'Óleo de Xisto (OTE) — alta fluidez, dispensa pré-aquecimento, baixa emissão', link: '/produtos/oleo-de-xisto/' },
        { texto: 'Óleo BTE — baixíssimo teor de enxofre (0,5%), premium Braskem, menor fuligem', link: '/produtos/oleo-bte/' },
        { texto: 'Óleos Alternativos — viscosidades variadas, sob medida para seu equipamento', link: '/produtos/oleos-alternativos/' },
      ],
    },
    {
      titulo: 'Aplicações Industriais do Óleo BPF',
      paragrafos: [
        'O óleo BPF é amplamente utilizado em diversos segmentos industriais que dependem de geração de calor para seus processos produtivos. Cada aplicação exige um perfil específico de combustível.',
      ],
      lista: [
        { texto: 'Caldeiras Industriais — geração de vapor para processos contínuos', link: '/solucoes/caldeiras/' },
        { texto: 'Usinas de Asfalto — secagem de agregados e produção de massa asfáltica', link: '/solucoes/usinas-de-asfalto/' },
        { texto: 'Fundições — alta carga térmica para fusão de metais', link: '/solucoes/fundicoes/' },
        { texto: 'Fornos Industriais — aquecimento de processos, secagem e tratamento térmico', link: '/solucoes/' },
        { texto: 'Secadores Industriais — aquecimento de ar para secagem de grãos e minerais', link: '/solucoes/' },
      ],
    },
    {
      titulo: 'Como Escolher o Óleo BPF Ideal',
      paragrafos: [
        'A escolha do óleo BPF ideal para sua operação depende de alguns fatores técnicos fundamentais:',
        '1. Tipo de equipamento: queimador, caldeira, forno ou secador — cada um tem exigências diferentes de viscosidade e atomização.',
        '2. Temperatura de operação: a viscosidade do combustível precisa ser compatível com a temperatura de trabalho do sistema de aquecimento.',
        '3. Exigências ambientais: indústrias sujeitas a limites de emissão de SOx precisam de óleos com baixo teor de enxofre (B1, BTE ou Xisto).',
        '4. Infraestrutura de armazenamento: tanques, linhas aquecidas e bombas precisam estar dimensionados para o tipo de combustível.',
        '5. Regime de operação: operações contínuas 24h exigem fornecimento programado e suporte técnico permanente.',
        'A Nuxem oferece suporte técnico gratuito para ajudar na especificação correta do combustível para seu equipamento.',
      ],
    },
    {
      titulo: 'Armazenamento e Manuseio Seguro',
      paragrafos: [
        'O armazenamento adequado do óleo BPF é essencial para preservar suas características e garantir segurança operacional:',
        '- Tanques devem ser dimensionados para o volume de consumo com folga mínima de 5 dias.',
        '- O óleo BPF requer aquecimento para manter a fluidez ideal para bombeamento (entre 40°C e 80°C, dependendo da viscosidade).',
        '- O ponto de fulgor do óleo BPF é acima de 66°C, o que exige cuidados com fontes de ignição próximas aos tanques.',
        '- A manutenção periódica dos tanques evita acúmulo de borra e contaminação do combustível.',
        '- Sistemas de contenção e drenagem devem seguir as normas ambientais vigentes.',
      ],
    },
    {
      titulo: 'Logística e Fornecimento',
      paragrafos: [
        'Uma operação térmica contínua não pode parar por falta de combustível. Por isso, a logística de fornecimento é tão importante quanto a qualidade do produto.',
        'A Nuxem trabalha com frota própria e produção sob demanda em todo o estado de São Paulo, garantindo:',
        '- Entrega programada conforme o consumo da sua planta',
        '- Atendimento 24 horas para emergências',
        '- Rastreabilidade completa de cada carga',
        '- Suporte técnico na especificação e no acompanhamento',
        '- Padrão constante de qualidade entre entregas',
      ],
    },
    {
      titulo: 'Perguntas Frequentes (FAQ)',
      ehFaq: true,
      perguntas: [
        { p: 'Qual a diferença entre óleo BPF e óleo APF?', r: 'O BPF tem Baixo Ponto de Fluidez (mantém fluidez em temperaturas mais baixas), enquanto o APF tem Alto Ponto de Fluidez. O BPF é mais viscoso e exige aquecimento, o APF é mais fluido e dispensa aquecimento prévio.' },
        { p: 'Óleo BPF é inflamável?', r: 'Sim, mas seu ponto de fulgor é acima de 66°C, o que o classifica como combustível (não inflamável) segundo a regulamentação brasileira. Isso significa que não entra em combustão espontânea em temperatura ambiente.' },
        { p: 'Qual o poder calorífico do óleo BPF?', r: 'O óleo BPF tem poder calorífico superior acima de 10.400 kcal/kg, um dos mais altos entre os combustíveis líquidos industriais disponíveis no Brasil.' },
        { p: 'Precisa aquecer o óleo BPF para usar?', r: 'Sim, o óleo BPF requer aquecimento entre 40°C e 80°C para reduzir sua viscosidade e permitir atomização adequada no queimador.' },
        { p: 'Qual a diferença entre BPF A1 e B1?', r: 'O BPF tipo A1 tem maior teor de enxofre (até 2,5%), enquanto o B1 tem teor reduzido (máx 1%). O B1 é indicado para indústrias com restrições ambientais.' },
        { p: 'Quanto tempo dura o óleo BPF armazenado?', r: 'Quando armazenado corretamente, o óleo BPF pode ser mantido por meses sem perda significativa de qualidade, desde que protegido de contaminação e com temperatura controlada.' },
      ],
    },
  ],
};